dist: trusty
language: node_js
cache: yarn
node_js:
  - '10'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$PATH"
  - psql -c 'create database universal_login_relayer_development;' -U postgres
install:
  - yarn install
script:
  - scripts/travis.sh
