version: 2.1

commands:
  build_monorepo:
    description: "Builds all packages in monorepo. Must be run in repo root."
    steps:
      - run: yarn build

jobs:
  lint_test_contracts_commons_ops:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run: yarn install
      - run: yarn lint
      - build_monorepo
      - run: cd universal-login-contracts && yarn test:nobuild
      - run: cd universal-login-commons && yarn test:nobuild
      - run: cd universal-login-ops && yarn test:nobuild
      - run: yarn codechecks
  test_sdk_relayer:
    docker:
      - image: circleci/node:10.15
        environment:
          PG_HOST: localhost
          PG_USER: postgres
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: universal_login_relayer_test
    steps:
      - checkout
      - run: yarn install
      - build_monorepo
      - run: cd universal-login-sdk && yarn test:nobuild
      - run: cd universal-login-relayer && yarn test:nobuild
  test_react_wallet_web3:
    docker:
      - image: circleci/node:10.15
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: universal_login_relayer_test
    steps:
      - checkout
      - run: yarn install
      - build_monorepo
      - run: cd universal-login-react && yarn test
      - run: cd universal-login-wallet && yarn test
      - run: cd universal-login-web3 && yarn test

workflows:
  version: 2
  universal_login_all:
    jobs:
      - lint_test_contracts_commons_ops
      - test_sdk_relayer
      - test_react_wallet_web3
