version: 2.1
commands:
  install-chrome-dependencies:
    steps:
      - run: sudo apt-get update
      - run: |
          sudo apt-get install -yq --no-install-recommends curl \
          libnss3 libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
          libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 \
          libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 \
          libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 \
  make-react-screenshots:
    steps:
      - run:
          name: Make React screenshots
          command: |
            cd universal-login-react;
            yarn start:dev & > /dev/null
            RETRY=0; set +e;
            while [ "$RETRY" != 60 ] && ! curl -s 0.0.0.0:8080 | grep -q "Universal Login React Playground"; do
              echo sleeping...
              sleep 1 && ((RETRY++));
            done;
            set -e; cd test; node screenshots.js
      - run:
          name: Make sure screenshots are taken
          command: |
            cd universal-login-react/test
            [ $(ls screenshots | grep .png | wc -l) -gt 0 ]
      - store_artifacts:
          path: universal-login-react/test/screenshots
          destination: screenshots
jobs:
  lint_test_contracts_commons_ops:
    docker:
      - image: circleci/node:11.15
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: cd universal-login-commons && yarn build && yarn test
      - run: cd universal-login-contracts && yarn build && yarn test
      - run: cd universal-login-relayer && yarn build
      - run: cd universal-login-ops && yarn build && yarn test
  test_sdk_relayer:
    docker:
      - image: circleci/node:11.15
        environment:
          PG_HOST: localhost
          PG_USER: postgres
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: universal_login_relayer_test
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: cd universal-login-commons && yarn build
      - run: cd universal-login-contracts && yarn build
      - run: cd universal-login-relayer && yarn build && yarn test
      - run: cd universal-login-sdk && yarn build && yarn test
  test_react_wallet_web3:
    docker:
      - image: circleci/node:11.15
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: universal_login_relayer_test
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: cd universal-login-react && yarn test
      - run: cd universal-login-wallet && yarn test
      - run: cd universal-login-web3 && yarn test
workflows:
  universal_login_all:
    jobs:
      - lint_test_contracts_commons_ops
      - test_sdk_relayer
      - test_react_wallet_web3
