version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run: yarn
      - save_cache:
            key: universal-login-{{ .Environment.CIRCLE_SHA1 }}
            paths:
              - ~/project
  lint:
    docker:
      - image: circleci/node:10.15
    steps:
      - restore_cache:
            keys: 
                - universal-login-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn lint
  test_commons:
    docker:
      - image: circleci/node:10.15
    steps:
      - restore_cache:
            keys: 
                - universal-login-{{ .Environment.CIRCLE_SHA1 }}
      - run: cd universal-login-commons && yarn test
  test_contracts:
    docker:
      - image: circleci/node:10.15
    steps:
      - restore_cache:
            keys: 
                - universal-login-{{ .Environment.CIRCLE_SHA1 }}
      - run: cd universal-login-contracts && yarn test
  test_relayer:
    docker:
      - image: circleci/node:10.15
        environment:
          PG_HOST: localhost
          PG_USER: postgres
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: universal_login_relayer_test
    steps:
      - restore_cache:
            keys: 
                - universal-login-{{ .Environment.CIRCLE_SHA1 }}
      - run: cd universal-login-relayer && yarn test
  test_ops:
    docker:
      - image: circleci/node:10.15
        environment:
          PG_HOST: localhost
          PG_USER: postgres
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: universal_login_relayer_test
    steps:
      - restore_cache:
            keys: 
                - universal-login-{{ .Environment.CIRCLE_SHA1 }}
      - run: cd universal-login-ops && yarn test
  test_sdk:
    docker:
      - image: circleci/node:10.15
        environment:
          PG_HOST: localhost
          PG_USER: postgres
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: universal_login_relayer_test
    steps:
      - restore_cache:
            keys: 
                - universal-login-{{ .Environment.CIRCLE_SHA1 }}
      - run: cd universal-login-sdk && yarn test
  test_example:
    docker:
      - image: circleci/node:10.15
        environment:
          PG_HOST: localhost
          PG_USER: postgres
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: universal_login_relayer_test
    steps:
      - restore_cache:
            keys: 
                - universal-login-{{ .Environment.CIRCLE_SHA1 }}
      - run: cd universal-login-example && yarn test
  test_wallet:
    docker:
      - image: circleci/node:10.15
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: universal_login_relayer_test
    steps:
      - restore_cache:
            keys: 
                - universal-login-{{ .Environment.CIRCLE_SHA1 }}
      - run: cd universal-login-wallet && yarn test
  run_klab:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run: sudo apt-get install make gcc maven openjdk-8-jdk flex pkg-config libmpfr-dev autoconf libtool pandoc zlib1g-dev z3 libz3-dev

workflows:
  version: 2
  formal_verification:
    jobs:
      - run_klab
  universal_login_all:
    jobs:
      - build
      - test_commons:
          requires:
            - build
      - test_contracts:
          requires:
            - build
      - test_example:
          requires:
            - build
      - test_ops:
          requires:
            - build
      - test_relayer:
          requires:
            - build
      - test_sdk:
          requires:
            - build
      - test_wallet:
          requires:
            - build
      - lint:
          requires:
            - build      


